shell = "zsh"

[plugins]

[plugins.autojump]
github = "wting/autojump"
dir = "bin"
apply = ["PATH", "source"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'

[plugins.completions]
github = 'zsh-users/zsh-completions'

[plugins.z]
github = 'agkozak/zsh-z'
